---

- hosts: firewalls
  gather_facts: true
  become: false
  vars_files:
    - variables.yml
  tasks:

    - name: Configure  Interfaces
      vyos.vyos.vyos_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
            enabled: "{{ item.enabled }}"
      loop: "{{ interfaces }}"
    
    - name: Configure Transit Bond
      vyos.vyos.vyos_config:
        lines:
          - set interfaces bonding bond0 member interface eth2 
          - set interfaces bonding bond0 member interface eth3
          - set interfaces bonding bond0 mode 802.3ad
          - set interfaces bonding bond0 address 10.125.0.1/24
        
    - name: Configure Transit Bond VIF {{ item.name }}
      vyos.vyos.vyos_config:
        lines:
          - "set interfaces bonding bond0 vif {{ item.number }} description '{{ item.name }}'"
          - "set interfaces bonding bond0 vif {{ item.number }} address {{ item.address }}"
      loop: "{{ vlans }}"
